package com.graphbuilder.model;

public enum TokenVertexCategory {
    // Control flow
    ANNOTATION_DECLARATION("ANNOTATION_DECL", 1),
    ARROW("ARROW", 2),
    BREAK("BREAK", 3),
    CASE("CASE", 4),
    CATCH("CATCH", 5),
    CLASS_DECLARATION("CLASS_DECL", 6),
    CONSTRUCTOR_DECLARATION("CONSTRUCTOR_DECL", 7),
    CONTINUE("CONTINUE", 8),
    DO("DO", 9),
    ELSE("ELSE", 10),
    ENUM_DECLARATION("ENUM_DECL", 11),
    ENUM_CONSTANT_DECLARATION("ENUM_CONST_DECL", 12),
    FINALLY("FINALLY", 13),
    GOTO("GOTO", 14),
    IF("IF", 15),
    INTERFACE_DECLARATION("INTERFACE_DECL", 16),
    FIELD_VAR_DECLARATION("FIELD_VAR_DECL", 17),
    FOR("FOR", 18),
    LAMBDA_VAR_DECLARATION("LAMBDA_VAR_DECL", 19),
    LOCAL_VAR_DECLARATION("LOCAL_VAR_DECL", 20),
    METHOD_DECLARATION("METHOD_DECL", 21),
    PARAM_VAR_DECLARATION("PARAM_VAR_DECL", 22),
    SWITCH("SWITCH", 23),
    SYNCHRONIZED("SYNCHRONIZED", 24),
    THROW("THROW", 25),
    TRY("TRY", 26),
    WHILE("WHILE", 27),

    // Data flow
    ARITHMETIC_ASSIGN("ARITHMETIC_ASSIGN", 28),
    ARRAY_CONSTRUCTOR_INVOCATION("ARRAY_CONSTRUCTOR_INV", 29),
    BINARY_ARITHMETICS("BINARY_ARITHMETICS", 30),
    BINARY_BIT("BINARY_BIT", 31),
    BINARY_LOGICS("BINARY_LOGICS", 32),
    BIT_ASSIGN("BIT_ASSIGN", 33),
    BIT_LOGIC("BIT_LOGIC", 34),
    BOOLEAN_LITERAL("BOOLEAN_LITERAL", 35),
    CHAR_LITERAL("CHAR_LITERAL", 36),
    CONSTRUCTOR_INVOCATION("CONSTRUCTOR_INV", 37),
    COMPARISON("COMPARISON", 38),
    DOUBLE_LITERAL("DOUBLE_LITERAL", 39),
    EQUAL("EQUAL", 40),
    EQUAL_EQUAL("EQUAL_EQUAL", 41),
    FLOAT_LITERAL("FLOAT_LITERAL", 42),
    GREATER("GREATER", 43),
    INSTANCE_OF("INSTANCE_OF", 44),
    INTEGER_LITERAL("INTEGER_LITERAL", 45),
    FIELD_VAR_ACCESS("FIELD_VAR_ACCESS", 46),
    METHOD_INVOCATION("METHOD_INV", 47),
    METHOD_REFERENCE("METHOD_REF", 48),
    LAMBDA_VAR_ACCESS("LAMBDA_VAR_ACCESS", 49),
    LESS("LESS", 50),
    LOCAL_VAR_ACCESS("LOCAL_VAR_ACCESS", 51),
    LONG_LITERAL("LONG_LITERAL", 52),
    NULL_LITERAL("NULL", 53),
    PARAM_VAR_ACCESS("PARAM_VAR_ACCESS", 54),
    RETURN("RETURN", 55),
    STRING_LITERAL("STRING_LITERAL", 56),
    UNARY_ARITHMETICS("UNARY_ARITHMETICS", 57),
    UNARY_LOGICS("UNARY_LOGICS", 58),

    // Syntax / AST
    AT("AT", 59),
    ABSTRACT("ABSTRACT", 60),
    ARRAY_TYPE_IDENTIFIER("ARRAY_TYPE_ID", 61),
    ASSERT("ASSERT", 62),
    CLASS("CLASS", 63),
    COLON("COLON", 64),
    COLON_COLON("COLON_COLON", 65),
    COMMA("COMMA", 66),
    CONST("CONST", 67),
    DEFAULT("DEFAULT", 68),
    DOT_TOKEN("DOT_TOKEN", 69),
    ELLIPSIS("ELLIPSIS", 70),
    ENUM("ENUM", 71),
    EXTENDS("EXTENDS", 72),
    FINAL("FINAL", 73),
    IMPLEMENTS("IMPLEMENTS", 74),
    IMPORT("IMPORT", 75),
    INTERFACE("INTERFACE", 76),
    TYPE_IDENTIFIER("TYPE_ID", 77),
    LBRACE("LBRACE", 78),
    LBRACK("LBRACK", 79),
    LPAREN("LPAREN", 80),
    NATIVE("NATIVE", 81),
    NEW("NEW", 82),
    PACKAGE("PACKAGE", 83),
    PRIVATE("PRIVATE", 84),
    PROTECTED("PROTECTED", 85),
    PUBLIC("PUBLIC", 86),
    RBRACE("RBRACE", 87),
    RBRACK("RBRACK", 88),
    RPAREN("RPAREN", 89),
    QUESTION("QUESTION", 90),
    SEMICOLON("SEMICOLON", 91),
    STATIC("STATIC", 92),
    SUPER("SUPER", 93),
    THIS("THIS", 94),
    THROWS("THROWS", 95),
    TILDE("TILDE", 96),
    TRANSIENT("TRANSIENT", 97),
    VOLATILE("VOLATILE", 98);

    private final String dotLabel;
    private final int code;

    TokenVertexCategory(String dotLabel, int code) {
        this.dotLabel = dotLabel;
        this.code = code;
    }

    public String dotLabel() {
        return dotLabel;
    }

    public int code() {
        return code;
    }
}
